# Generated by Django 3.1.7 on 2021-03-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcode_code', models.CharField(max_length=8)),
                ('listing_count', models.IntegerField()),
                ('average_daily_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NexusOutcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcode_code', models.CharField(max_length=8)),
                ('listing_count', models.IntegerField()),
                ('average_daily_rate', models.FloatField()),
                ('distance_1', models.CharField(blank=True, max_length=8, null=True)),
                ('distance_2', models.CharField(blank=True, max_length=8, null=True)),
                ('distance_3', models.CharField(blank=True, max_length=8, null=True)),
                ('distance_4', models.CharField(blank=True, max_length=8, null=True)),
                ('distance_5', models.CharField(blank=True, max_length=8, null=True)),
                ('distance_6', models.CharField(blank=True, max_length=8, null=True)),
                ('distance_7', models.CharField(blank=True, max_length=8, null=True)),
                ('distance_8', models.CharField(blank=True, max_length=8, null=True)),
                ('distance_9', models.CharField(blank=True, max_length=8, null=True)),
                ('distance_10', models.CharField(blank=True, max_length=8, null=True)),
                ('next_outcode_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nexus1', to='postcodes.outcode')),
                ('next_outcode_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nexus10', to='postcodes.outcode')),
                ('next_outcode_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nexus2', to='postcodes.outcode')),
                ('next_outcode_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nexus3', to='postcodes.outcode')),
                ('next_outcode_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nexus4', to='postcodes.outcode')),
                ('next_outcode_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nexus5', to='postcodes.outcode')),
                ('next_outcode_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nexus6', to='postcodes.outcode')),
                ('next_outcode_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nexus7', to='postcodes.outcode')),
                ('next_outcode_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nexus8', to='postcodes.outcode')),
                ('next_outcode_9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nexus9', to='postcodes.outcode')),
            ],
        ),
    ]
